import { useState, useEffect } from "react";
import { FiFileText, FiTrendingUp, FiCheckCircle, FiClock, FiAlertCircle, FiDownload, FiPrinter, FiLayers, FiPieChart, FiBarChart2, FiActivity, FiSearch, FiArrowUpRight, FiZap } from "react-icons/fi";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { API_URL } from "../config";

export default function Reports() {
  const [reportType, setReportType] = useState("summary");
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const user = JSON.parse(localStorage.getItem("user") || "{}");
  const isAdmin = user.role?.toLowerCase() === 'admin';

  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true);
        let data = [];
        if (isAdmin) {
          const res = await fetch(`${API_URL}/requests`);
          if (res.ok) data = await res.json();
        } else if (user.role?.toLowerCase() === 'staff') {
          const assignedRes = await fetch(`${API_URL}/assigned-requests/${user._id}`);
          if (assignedRes.ok) data = await assignedRes.json();
        } else {
          const res = await fetch(`${API_URL}/user-requests/${user._id}`);
          if (res.ok) {
            const result = await res.json();
            data = result.requests || [];
          }
        }
        setRequests(data || []);
      } catch (err) {
        setError("Synchronization failure. System analytics offline.");
      } finally {
        setLoading(false);
      }
    }
    fetchData();
  }, [isAdmin, user._id, user.role]);

  const calculateStats = () => {
    const total = requests?.length || 0;
    if (total === 0) return null;

    const completed = requests.filter(r => r && (r.status === 'Approved' || r.status === 'Resolved')).length;
    const inProgress = requests.filter(r => r && r.status === 'In Progress').length;
    const pending = requests.filter(r => r && r.status === 'Pending').length;
    const rejected = requests.filter(r => r && r.status === 'Rejected').length;

    const priorityData = ["High", "Medium", "Low"].map(p => {
      const count = requests.filter(r => r && r.priority === p).length;
      return { priority: p, count, percentage: Math.round((count / total) * 100) || 0 };
    });

    const categoryMap = {};
    requests.forEach(r => {
      const cat = r.department || r.category || "General";
      categoryMap[cat] = (categoryMap[cat] || 0) + 1;
    });
    const categoryData = Object.keys(categoryMap).map(cat => ({
      category: cat,
      count: categoryMap[cat],
      percentage: Math.round((categoryMap[cat] / total) * 100) || 0
    })).sort((a, b) => b.count - a.count);

    return {
      total, completed, inProgress, pending, rejected,
      priority: priorityData,
      category: categoryData,
      efficiency: Math.round((completed / total) * 100) || 0
    };
  };

  const stats = calculateStats();

  const handleDownloadPDF = () => {
    if (!stats) return;
    const doc = new jsPDF();
    doc.setFontSize(22);
    doc.setTextColor(79, 70, 229);
    doc.text("Executive Performance Intelligence", 14, 22);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by: ${user.name} | ${new Date().toLocaleString()}`, 14, 30);

    autoTable(doc, {
      startY: 40,
      head: [["Operational Metric", "Volume", "Current State"]],
      body: [
        ["Total Logged Requests", stats.total, "Synchronized"],
        ["Resolved Missions", stats.completed, "Verified"],
        ["Active Operational Cycle", stats.inProgress, "Live"],
        ["System Rejections", stats.rejected, "Documented"]
      ],
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229] }
    });

    doc.save(`SRLM_Intelligence_${Date.now()}.pdf`);
  };

  if (loading) return <div className="p-5 text-center d-flex flex-column align-items-center gap-3">
    <div className="spinner-border text-primary shadow-sm" />
    <span className="fw-bold text-muted small uppercase">Calibrating Analytics...</span>
  </div>;

  return (
    <div className="container-fluid pt-4 pb-5 px-lg-5 animate-fade-in">
      {/* Executive Intelligence Header */}
      <div className="d-flex flex-wrap justify-content-between align-items-center mb-5 gap-4 border-bottom pb-4">
        <div>
           <div className="d-flex align-items-center gap-3 mb-1">
              <div className="p-2.5 grad-indigo rounded-circle text-white shadow-sm"><FiZap size={22} /></div>
              <div>
                 <h2 className="mb-0 fw-bold text-dark outfit-font">Intelligence Console</h2>
                 <p className="text-muted small mb-0">High-fidelity performance metrics and cross-departmental analytics.</p>
              </div>
           </div>
        </div>
        <div className="d-flex gap-2">
            <button className="btn btn-outline-secondary btn-sm px-3 rounded-pill fw-bold border-2 d-flex align-items-center bg-white transition-all hover-up" onClick={() => window.print()}>
               <FiPrinter className="me-2" /> Print Sheet
            </button>
            <button className="btn btn-primary btn-sm px-4 rounded-pill fw-bold shadow-sm d-flex align-items-center grad-indigo border-0 transition-all hover-up text-white" onClick={handleDownloadPDF} disabled={!stats}>
               <FiDownload className="me-2" /> Export Intel
            </button>
        </div>
      </div>

      {!stats ? (
          <div className="text-center py-5 bg-white rounded-5 shadow-sm border border-dashed animate-up">
             <FiLayers size={48} className="text-muted opacity-25 mb-4" />
             <h4 className="fw-bold text-dark">Awaiting Operational Data</h4>
             <p className="text-muted px-4 mx-auto" style={{ maxWidth: '450px' }}>The intelligence console requires active system requests to generate performance tracking and strategic reports.</p>
          </div>
      ) : (
          <div className="animate-up">
            {/* Navigation Pills - Matches Screenshot */}
            <div className="d-inline-flex p-1 bg-white border border-opacity-50 rounded-pill shadow-sm mb-5">
               {['Summary', 'Priority', 'Category'].map(tab => (
                   <button 
                      key={tab}
                      className={`btn btn-sm px-5 py-2.5 rounded-pill fw-bold border-0 transition-all ${reportType === tab.toLowerCase() ? 'grad-indigo text-white shadow' : 'btn-light text-muted bg-white'}`}
                      onClick={() => setReportType(tab.toLowerCase())}
                   >
                      {tab}
                   </button>
               ))}
            </div>

            {/* View Layer Controller - Compact Mode */}
            {reportType === "summary" && (
                <div className="row g-3 mb-4">
                   {/* Strategic Cards - Compact */}
                   {[
                      { label: "Total Requests", value: stats.total, icon: <FiFileText />, color: "indigo", unit: "Requests" },
                      { label: "Success Rate", value: `${stats.efficiency}%`, icon: <FiCheckCircle />, color: "emerald", unit: "Resolved" },
                      { label: "High Priority", value: stats.priority.find(p => p.priority === 'High')?.count || 0, icon: <FiAlertCircle />, color: "rose", unit: "Critical" },
                      { label: "In Progress", value: stats.inProgress, icon: <FiClock />, color: "amber", unit: "Active Tasks" }
                   ].map(card => (
                       <div key={card.label} className="col-md-3">
                          <div className={`clean-card card-interactive card-accent-${card.color} p-3`}>
                             <div className="d-flex justify-content-between align-items-start mb-2">
                                <div className={`p-2 rounded-3 bg-${card.color} bg-opacity-10 text-${card.color} shadow-sm`}><div style={{ transform: 'scale(1.0)' }}>{card.icon}</div></div>
                                <div className="text-end">
                                   <div className="text-muted small fw-bold text-uppercase" style={{ fontSize: '9px', letterSpacing: '0.5px' }}>{card.label}</div>
                                   <div className={`fw-bold text-${card.color} small`} style={{ fontSize: '11px' }}>{card.unit}</div>
                                </div>
                             </div>
                             <h3 className="fw-black text-dark mb-0 outfit-font" style={{ fontSize: '1.8rem' }}>{card.value}</h3>
                          </div>
                       </div>
                   ))}

                   {/* Efficiency Center - Compact */}
                   <div className="col-lg-8">
                      <div className="card border-0 shadow-sm rounded-4 overflow-hidden h-100 position-relative">
                         <div className="card-body p-4">
                            <div className="d-flex justify-content-between align-items-center mb-4">
                               <h6 className="fw-bold outfit-font mb-0 d-flex align-items-center gap-2 small"><FiActivity className="text-primary" /> System Performance Overview</h6>
                               <button className="btn btn-sm btn-light border rounded-pill px-3 fw-bold" style={{ fontSize: '11px' }}>Q2 Analysis <FiArrowUpRight /></button>
                            </div>
                            
                            <div className="row g-4 align-items-center">
                               <div className="col-md-6">
                                  <div className="mb-3">
                                     <div className="d-flex justify-content-between mb-1 small fw-bold" style={{ fontSize: '11px' }}>
                                        <span>System Utilization</span>
                                        <span className="text-primary">{Math.round((stats.inProgress / stats.total) * 100)}%</span>
                                     </div>
                                     <div className="progress rounded-pill bg-light shadow-inner" style={{ height: '6px' }}>
                                        <div className="progress-bar grad-indigo rounded-pill shadow-sm" style={{ width: `${(stats.inProgress / stats.total) * 100}%` }}></div>
                                     </div>
                                  </div>
                                  <div>
                                     <div className="d-flex justify-content-between mb-1 small fw-bold" style={{ fontSize: '11px' }}>
                                        <span>Resolution Rate</span>
                                        <span className="text-success">{stats.efficiency}%</span>
                                     </div>
                                     <div className="progress rounded-pill bg-light shadow-inner" style={{ height: '6px' }}>
                                        <div className="progress-bar grad-emerald rounded-pill shadow-sm" style={{ width: `${stats.efficiency}%` }}></div>
                                     </div>
                                  </div>
                               </div>
                               <div className="col-md-6 border-start border-opacity-10 ps-md-4">
                                  <div className="p-3 bg-light rounded-3 border border-dashed border-2">
                                     <FiTrendingUp className="text-primary mb-1" size={20} />
                                     <h6 className="fw-bold text-dark small">Optimization Insight</h6>
                                     <p className="text-muted mb-0 fw-medium" style={{ fontSize: '12px' }}>Resolution speed is currently {stats.efficiency > 70 ? 'High' : 'Stable'}. Overall system load is {stats.total > 50 ? 'Significant' : 'Optimal'}.</p>
                                  </div>
                               </div>
                            </div>
                         </div>
                      </div>
                   </div>

                   <div className="col-lg-4">
                      <div className="card grad-indigo text-white border-0 rounded-4 shadow-lg h-100 p-3">
                         <div className="card-body d-flex flex-column h-100 py-2 text-center">
                            <div className="mb-auto">
                               <div className="p-2.5 bg-white bg-opacity-10 d-inline-block rounded-circle mb-3 border border-white border-opacity-10"><FiZap size={22} /></div>
                               <h6 className="fw-bold outfit-font border-bottom border-white border-opacity-10 pb-2 mb-3 small">Service Efficacy</h6>
                            </div>
                            <div className="my-auto py-2">
                               <h1 className="fw-black mb-0 outfit-font" style={{ fontSize: '2.5rem' }}>{stats.efficiency}%</h1>
                               <div className="text-uppercase small fw-bold opacity-75 mt-1" style={{ letterSpacing: '1px', fontSize: '10px' }}>Total Efficiency</div>
                            </div>
                            <div className="mt-auto">
                               <div className="p-2 bg-white bg-opacity-10 rounded-pill fw-bold border border-white border-opacity-10" style={{ fontSize: '11px' }}>Efficiency Benchmark</div>
                            </div>
                         </div>
                      </div>
                   </div>
                </div>
            )}

            {reportType === "priority" && (
                <div className="row g-3 animate-fade-in">
                   {stats.priority.map(p => (
                       <div key={p.priority} className="col-md-4">
                          <div className="clean-card p-4 text-center h-100 card-interactive">
                             <div className={`mx-auto mb-3 rounded-circle bg-${p.priority === 'High' ? 'rose' : p.priority === 'Medium' ? 'amber' : 'emerald'} bg-opacity-10 border border-${p.priority === 'High' ? 'rose' : p.priority === 'Medium' ? 'amber' : 'emerald'} border-opacity-25 d-flex align-items-center justify-content-center shadow-sm`} style={{ width: '50px', height: '50px' }}>
                                <FiBarChart2 className={`text-${p.priority === 'High' ? 'rose' : p.priority === 'Medium' ? 'amber' : 'emerald'}`} size={20} />
                             </div>
                             <h6 className="fw-black text-dark text-uppercase small mb-1" style={{ fontSize: '10px', letterSpacing: '1px' }}>{p.priority} Intensity</h6>
                             <h1 className="fw-black text-dark outfit-font mb-1" style={{ fontSize: '2rem' }}>{p.count}</h1>
                             <div className={`fw-bold small text-${p.priority === 'High' ? 'rose' : p.priority === 'Medium' ? 'amber' : 'emerald'} mb-3`} style={{ fontSize: '11px' }}>{p.percentage}% System Allocation</div>
                             <div className="progress rounded-pill bg-light" style={{ height: '6px' }}>
                                <div className={`progress-bar grad-${p.priority === 'High' ? 'rose' : p.priority === 'Medium' ? 'amber' : 'emerald'} rounded-pill shadow-sm`} style={{ width: `${p.percentage}%` }}></div>
                             </div>
                          </div>
                       </div>
                   ))}
                </div>
            )}

            {reportType === "category" && (
                <div className="card shadow-sm border-0 rounded-4 overflow-hidden bg-white animate-fade-in">
                   <div className="card-header bg-white py-4 px-4 border-0 d-flex justify-content-between align-items-center">
                      <div>
                         <h6 className="mb-0 fw-black text-dark outfit-font d-flex align-items-center gap-2"><FiPieChart className="text-primary" /> Category Distribution</h6>
                         <p className="text-muted fw-bold mb-0" style={{ fontSize: '11px' }}>Distribution across {stats.category.length} operational clusters.</p>
                      </div>
                      <div className="bg-light p-1 px-3 rounded-pill border fw-bold small text-primary" style={{ fontSize: '10px' }}>SYSTEM LOAD</div>
                   </div>
                   <div className="card-body p-4 pt-0">
                      <div className="row g-3">
                         {stats.category.map(c => (
                             <div key={c.category} className="col-md-6 col-lg-4">
                                <div className="p-3 bg-light bg-opacity-50 rounded-3 border border-white h-100 shadow-inner">
                                   <div className="d-flex justify-content-between align-items-center mb-2">
                                      <span className="fw-black text-dark text-uppercase" style={{ fontSize: '10px', letterSpacing: '0.05em' }}>{c.category}</span>
                                      <span className="badge bg-white shadow-sm border text-primary fw-bold px-2 py-1" style={{ fontSize: '10px' }}>{c.count}</span>
                                   </div>
                                   <div className="progress bg-white rounded-pill mb-1" style={{ height: '4px' }}>
                                      <div className="progress-bar grad-indigo rounded-pill" style={{ width: `${c.percentage}%` }}></div>
                                   </div>
                                   <div className="text-end">
                                      <span className="text-muted fw-bold" style={{ fontSize: '9px' }}>{c.percentage}% LOAD</span>
                                   </div>
                                </div>
                             </div>
                         ))}
                      </div>
                   </div>
                </div>
            )}
          </div>
      )}
    </div>
  );
}
